import type { TestRecord } from "./types"

// Generate comprehensive dummy data matching the CSV structure
export function generateDummyData(): TestRecord[] {
  const now = new Date()
  const locations = ["Lagos", "Abuja", "Kano", "Port Harcourt", "Ibadan", "Kaduna", "Rivers", "Katsina", "Enugu", "Oyo"]

  const records: TestRecord[] = [
    // Voice calls - MTN
    {
      testCaseDescription: "LAG2PHV",
      originatorNumber: "2348030001234",
      originatorLocation: "Lagos",
      originatorNetwork: "MTN",
      originatorServiceType: "Voice Mobile Originating",
      recipientNumber: "2348023001234",
      recipientLocation: "Port Harcourt",
      recipientNetwork: "AIRTEL",
      recipientServiceType: "Voice Mobile Terminating",
      service: "Voice",
      timestamp: new Date(now.getTime() - 3600000).toISOString(),
      duration: "15secs",
      callSetupTime: "2.56 sec",
      status: "Success",
      failureCause: "-",
      dataSpeed: "NA",
    },
    {
      testCaseDescription: "LAG2PHV",
      originatorNumber: "2348030001234",
      originatorLocation: "Lagos",
      originatorNetwork: "MTN",
      originatorServiceType: "Voice Mobile Originating",
      recipientNumber: "2348023001234",
      recipientLocation: "Port Harcourt",
      recipientNetwork: "AIRTEL",
      recipientServiceType: "Voice Mobile Terminating",
      service: "Voice",
      timestamp: new Date(now.getTime() - 2800000).toISOString(),
      duration: "35secs",
      callSetupTime: "1.78 secs",
      status: "Failed",
      failureCause: "Dropped Call",
      dataSpeed: "NA",
    },
    {
      testCaseDescription: "LAG2PHV",
      originatorNumber: "2348030001234",
      originatorLocation: "Lagos",
      originatorNetwork: "MTN",
      originatorServiceType: "Voice Mobile Originating",
      recipientNumber: "2348023001234",
      recipientLocation: "Port Harcourt",
      recipientNetwork: "AIRTEL",
      recipientServiceType: "Voice Mobile Terminating",
      service: "Voice",
      timestamp: new Date(now.getTime() - 2400000).toISOString(),
      duration: "30min",
      callSetupTime: "1.23sec",
      status: "Success",
      failureCause: "-",
      dataSpeed: "NA",
    },

    // Voice calls - GLO to T2
    {
      testCaseDescription: "ABJ2KANOV",
      originatorNumber: "2348054001234",
      originatorLocation: "Abuja",
      originatorNetwork: "GLO",
      originatorServiceType: "Voice Mobile Originating",
      recipientNumber: "2348095001234",
      recipientLocation: "Kano",
      recipientNetwork: "T2",
      recipientServiceType: "Voice Mobile Terminating",
      service: "Voice",
      timestamp: new Date(now.getTime() - 2000000).toISOString(),
      duration: "62secs",
      callSetupTime: "2.8 secs",
      status: "Success",
      failureCause: "-",
      dataSpeed: "NA",
    },
    {
      testCaseDescription: "KANO2ABJV",
      originatorNumber: "2348095001234",
      originatorLocation: "Kano",
      originatorNetwork: "T2",
      originatorServiceType: "Voice Mobile Originating",
      recipientNumber: "2348054001234",
      recipientLocation: "Abuja",
      recipientNetwork: "GLO",
      recipientServiceType: "Voice Mobile Terminating",
      service: "Voice",
      timestamp: new Date(now.getTime() - 1600000).toISOString(),
      duration: "32secs",
      callSetupTime: "1.2 secs",
      status: "Success",
      failureCause: "-",
      dataSpeed: "NA",
    },
    {
      testCaseDescription: "ABJ2KANOV",
      originatorNumber: "2348054001234",
      originatorLocation: "Abuja",
      originatorNetwork: "GLO",
      originatorServiceType: "Voice Mobile Originating",
      recipientNumber: "2348095001234",
      recipientLocation: "Kano",
      recipientNetwork: "T2",
      recipientServiceType: "Voice Mobile Terminating",
      service: "Voice",
      timestamp: new Date(now.getTime() - 1200000).toISOString(),
      duration: "45secs",
      callSetupTime: "3.1 secs",
      status: "Failed",
      failureCause: "Unable to Connect",
      dataSpeed: "NA",
    },

    // SMS records
    {
      testCaseDescription: "IB2KAD",
      originatorNumber: "2348030001235",
      originatorLocation: "Ibadan",
      originatorNetwork: "MTN",
      originatorServiceType: "SMS Mobile Originating",
      recipientNumber: "2348023001234",
      recipientLocation: "Kaduna",
      recipientNetwork: "AIRTEL",
      recipientServiceType: "SMS Mobile Terminating",
      service: "SMS",
      timestamp: new Date(now.getTime() - 900000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "SUBMITTED AND DELIVERED",
      failureCause: "-",
      dataSpeed: "NA",
    },
    {
      testCaseDescription: "KAD2IB",
      originatorNumber: "2348030001230",
      originatorLocation: "Kaduna",
      originatorNetwork: "MTN",
      originatorServiceType: "SMS Mobile Originating",
      recipientNumber: "2348023001234",
      recipientLocation: "Ibadan",
      recipientNetwork: "AIRTEL",
      recipientServiceType: "SMS Mobile Terminating",
      service: "SMS",
      timestamp: new Date(now.getTime() - 600000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "Failed",
      failureCause: "SMS not Delivered",
      dataSpeed: "NA",
    },
    {
      testCaseDescription: "ABJ2KANOS",
      originatorNumber: "2348054001234",
      originatorLocation: "Abuja",
      originatorNetwork: "GLO",
      originatorServiceType: "SMS Mobile Originating",
      recipientNumber: "2348095001234",
      recipientLocation: "Kano",
      recipientNetwork: "T2",
      recipientServiceType: "SMS Mobile Terminating",
      service: "SMS",
      timestamp: new Date(now.getTime() - 300000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "SUBMITTED",
      failureCause: "-",
      dataSpeed: "NA",
    },
    {
      testCaseDescription: "KANO2ABJS",
      originatorNumber: "2348095001234",
      originatorLocation: "Kano",
      originatorNetwork: "T2",
      originatorServiceType: "SMS Mobile Originating",
      recipientNumber: "2348054001234",
      recipientLocation: "Abuja",
      recipientNetwork: "GLO",
      recipientServiceType: "SMS Mobile Terminating",
      service: "SMS",
      timestamp: new Date(now.getTime() - 100000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "SUBMITTED AND DELIVERED",
      failureCause: "-",
      dataSpeed: "NA",
    },

    // Data tests
    {
      testCaseDescription: "ABJData",
      originatorNumber: "2348054001234",
      originatorLocation: "Abuja",
      originatorNetwork: "GLO",
      originatorServiceType: "Data Speed Test",
      recipientNumber: "NA",
      recipientLocation: "NA",
      recipientNetwork: "GLO",
      recipientServiceType: "NA",
      service: "Data",
      timestamp: new Date(now.getTime() - 5400000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "Success",
      failureCause: "-",
      dataSpeed: "78Mbps",
    },
    {
      testCaseDescription: "ABJData",
      originatorNumber: "2348054001234",
      originatorLocation: "Abuja",
      originatorNetwork: "GLO",
      originatorServiceType: "Data Speed Test",
      recipientNumber: "NA",
      recipientLocation: "NA",
      recipientNetwork: "GLO",
      recipientServiceType: "NA",
      service: "Data",
      timestamp: new Date(now.getTime() - 4800000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "Success",
      failureCause: "-",
      dataSpeed: "102Mbps",
    },
    {
      testCaseDescription: "ABJData",
      originatorNumber: "2348054001234",
      originatorLocation: "Abuja",
      originatorNetwork: "GLO",
      originatorServiceType: "Data Speed Test",
      recipientNumber: "NA",
      recipientLocation: "NA",
      recipientNetwork: "GLO",
      recipientServiceType: "NA",
      service: "Data",
      timestamp: new Date(now.getTime() - 4000000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "Failed",
      failureCause: "No Internet Access",
      dataSpeed: "0",
    },
    {
      testCaseDescription: "KanoData",
      originatorNumber: "2348095001234",
      originatorLocation: "Kano",
      originatorNetwork: "T2",
      originatorServiceType: "Data Speed Test",
      recipientNumber: "NA",
      recipientLocation: "NA",
      recipientNetwork: "T2",
      recipientServiceType: "NA",
      service: "Data",
      timestamp: new Date(now.getTime() - 3600000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "Success",
      failureCause: "-",
      dataSpeed: "237Mbps",
    },
    {
      testCaseDescription: "KanoData",
      originatorNumber: "2348095001234",
      originatorLocation: "Kano",
      originatorNetwork: "T2",
      originatorServiceType: "Data Speed Test",
      recipientNumber: "NA",
      recipientLocation: "NA",
      recipientNetwork: "T2",
      recipientServiceType: "NA",
      service: "Data",
      timestamp: new Date(now.getTime() - 3000000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "Success",
      failureCause: "-",
      dataSpeed: "120Mbps",
    },
    {
      testCaseDescription: "LagosData",
      originatorNumber: "2348030001111",
      originatorLocation: "Lagos",
      originatorNetwork: "MTN",
      originatorServiceType: "Data Speed Test",
      recipientNumber: "NA",
      recipientLocation: "NA",
      recipientNetwork: "MTN",
      recipientServiceType: "NA",
      service: "Data",
      timestamp: new Date(now.getTime() - 2400000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "Success",
      failureCause: "-",
      dataSpeed: "216Mbps",
    },
    {
      testCaseDescription: "LagosData",
      originatorNumber: "2348030001111",
      originatorLocation: "Lagos",
      originatorNetwork: "MTN",
      originatorServiceType: "Data Speed Test",
      recipientNumber: "NA",
      recipientLocation: "NA",
      recipientNetwork: "MTN",
      recipientServiceType: "NA",
      service: "Data",
      timestamp: new Date(now.getTime() - 1800000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "Failed",
      failureCause: "No Internet Access",
      dataSpeed: "-",
    },
    {
      testCaseDescription: "LagosData",
      originatorNumber: "2348030001111",
      originatorLocation: "Lagos",
      originatorNetwork: "MTN",
      originatorServiceType: "Data Speed Test",
      recipientNumber: "NA",
      recipientLocation: "NA",
      recipientNetwork: "MTN",
      recipientServiceType: "NA",
      service: "Data",
      timestamp: new Date(now.getTime() - 1200000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "Success",
      failureCause: "-",
      dataSpeed: "34Mbps",
    },
    {
      testCaseDescription: "IBData",
      originatorNumber: "2348030001200",
      originatorLocation: "Ibadan",
      originatorNetwork: "MTN",
      originatorServiceType: "Data Speed Test",
      recipientNumber: "NA",
      recipientLocation: "NA",
      recipientNetwork: "MTN",
      recipientServiceType: "NA",
      service: "Data",
      timestamp: new Date(now.getTime() - 600000).toISOString(),
      duration: "NA",
      callSetupTime: "NA",
      status: "Success",
      failureCause: "-",
      dataSpeed: "89Mbps",
    },
  ]

  return records
}
